server: 
 port: 8082
#spring boot configuration
spring:
  application:
    name: organizationservice
  profiles:
    active: default
  cloud:
    enabled: true
#jasypt key
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: microservice
    
#database   
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/microserviceInAction?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ENC(jxnoq5X3grqR6ZtQBQIejbHmNufNKAE/)
    password: ENC(ADEPnfj6jdl2kPsl/Kjb8WLShNRAy4be) 

#JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 #   database: postgres
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect   
      validation-query: "select 1"
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
