server: 
 port: 8081
#spring boot configuration
spring:
  application:
    name: licensingservice
  profiles:
    active: default
  cloud:
    config:
      enabled: true
eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url: 
       defaultZone: http://localhost:8761/eureka/   
 
#jasypt key
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: microservice
#Application properties
example:
  property: licensingservice_test_properties
#database   
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/microserviceInAction?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ENC(jxnoq5X3grqR6ZtQBQIejbHmNufNKAE/)
    password: ENC(ADEPnfj6jdl2kPsl/Kjb8WLShNRAy4be) 


#JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 #   database: postgres
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect   
      validation-query: "select 1"
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug

