server: 
 port: 8081
#database   
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/microserviceInAction?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ENC(8Ssw28bO6cOTkwx+ZYFg9fxlC2lD9yZ0)
    password: ENC(N3h2iD4mZBYXWjTqhAcjlUd78cwpYw6M)
#JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 #   database: postgres
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect   
      validation-query: "select 1"
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
   '[org.springframework]': info
   '[org.hibernate]': debug 
#jasypt key
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: microservice
example:
  property: licensingservice_test_properties
